services:
  express:
    build: ./express
    restart: unless-stopped

  fastify:
    build: ./fastify
    restart: unless-stopped

  nest:
    build: ./nest
    restart: unless-stopped

  django:
    build: ./django
    restart: unless-stopped

  spring-boot:
    build: ./spring-boot
    restart: unless-stopped

  elysia:
    build: ./elysia
    restart: unless-stopped

  runner:
    build: ./runner
    depends_on:
      - express
      - fastify
      - nest
      - django
      - spring-boot
      - elysia
    restart: unless-stopped

  gateway:
    build: ./gateway
    depends_on:
      - express
      - fastify
      - nest
      - django
      - spring-boot
      - elysia
      - runner
    restart: unless-stopped
